=== elyabe306/atividades-pos-2024/xml/definicoes.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT cardapio (prato+)>
<!ELEMENT prato (nome,descr,ingr,preco,caloria,tempo)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descr (#PCDATA)>
<!ELEMENT ingr (ing+)>
<!ELEMENT ing (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT caloria (#PCDATA)>
<!ELEMENT tempo (#PCDATA)>
<!ATTLIST prato id ID #REQUIRED>
<!ATTLIST preco moeda (USA|BRL) #REQUIRED>

=== elyabe306/atividades-pos-2024/xml/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">
<cardapio>
    
    <prato id="tt">
        <nome>
            Tanajura c/Tapioca
        </nome>
        <descr>
            A carne adocicada de tanajura frita em banha de porco com pimenta do reino numa fatia de tapioca feita tradicionalmente
        </descr>
        <ingr>
            Tanajura, pimenta do reino, goma, manteiga, banha de porco
        </ingr>
        <preco>
            5,00
        </preco>
        <caloria>
            600 
        </caloria>
        <tempo>
            5 minutos
        </tempo>
    </prato>
    <prato id="te">
        <nome>
            Tejo cozido
        </nome>
        <descr>
            Tejo inteiro cozido deliciosamente
        </descr>
        <ingr>
            Tejo, cebola, pimentão, pimenta do reino
        </ingr>
        <preco>
            90,00
        </preco>
        <caloria>
            900
        </caloria>
        <tempo>
            1 hora
        </tempo>
    </prato>
    <prato id="sc">
        <nome>
            Sopa de Cebola
        </nome>
        <descr>
            Uma sopa tentadora e diferente, gostosíssima
        </descr>
        <ingr>
            Cebola, vinho branco, pimenta do reino, farinha de milho, lemon pepper
        </ingr>
        <preco>
            20,00
        </preco>
        <caloria>
            700
        </caloria>
        <tempo>
            1 hora
        </tempo>
    </prato>
    <prato id="pt">
        <nome>
            Pato no Tucupi
        </nome>
        <descr>
            Comer pato é coisa comum no Pará, e o pato no tucupi está sempre na mesa em dias de festa. 
            É considerado o prato que não pode faltar no círio de Nazaré, uma das maiores festas religiosas do país. 
            Existem muitos criadores de pato no Pará, alguns apuram a raça a partir de vários cruzamentos, 
            inclusive com patos selvagens, a carne é escura e firme preparado com vários temperos, 
            o pato é assado cortado em pedaços e mergulhado no tucupi, um caldo amarelo extraído da mandioca, 
            o último toque vem do jambu, planta picante que provoca ligeira dormência na boca 
            e que faz parte de muitas receitas da cozinha paraense.
        </descr>
        <ingr>
            Pato, tucupi, pimenta do reino
        </ingr>
        <preco>
            100,00
        </preco>
        <caloria>
            666
        </caloria>
        <tempo>
            2 horas
        </tempo>
    </prato>
    <prato id="pa">
        <nome>
            Pão assado
        </nome>
        <descr>
            Pão assado
        </descr>
        <ingr>
            Pão e manteiga
        </ingr>
        <preco>
            1,00
        </preco>
        <caloria>
            200
        </caloria>
        <tempo>
            1 minuto
        </tempo>
    </prato>
</cardapio>
